%{
 Plots the Histogram from the matrix generated by the relative stability
 analysis function i.e. "odecode_relative_stability_N.m". This function 
 has to be changed manually each time for different plots.
%}

%load final_table_FOUR_SA_SA.mat
y = [final_table(:,2),final_table(:,3)]; y = y ./ 1000;
Y1 = y(:,1);Y2 = y(:,2);
figure;
[Data1,x1] = hist(Y1,100);
[Data2,x2] = hist(Y2,100);

Data1 = Data1./sum(Data1); Data2 = Data2./sum(Data2);
bar(x1,Data1,'FaceColor',[0 0 0]); 
hold on; bar(x2,Data2,'FaceColor',[0.8 0.8 0.8]);
ylim([0,0.3]); % SHOULD BE SET ACCORDINGLY EVERY TIME
title('FOUR: 6-11 state (0.0-1.0)')
%saveas(gcf,'FOUR-bi-full.fig')
%saveas(gcf,'FOUR-bi-full.jpg')

figure
data1 = Data1(5:95); data2 = Data2(5:95); x1 = x1(5:95);
bar(x1,data1,'FaceColor',[0 0 0])
hold on
bar(x1,data2,'FaceColor',[0.8 0.8 0.8])
ylim([0,0.025]); % SHOULD BE SET ACCORDINGLY EVERY TIME
title('FOUR: 6-11 state (0.045-0.955)')
%saveas(gcf,'FOUR-bi-mid.fig')
%saveas(gcf,'FOUR-bi-mid.jpg')

ExtremeData = ((sum(Data1) - sum(data1)) + (sum(Data2) - sum(data2)))/2



